apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgRemover
spec:
  selector:
    matchLabels:
      app: bgRemover
  template:
    metadata:
      labels:
        app: bgRemover
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
      containers:
      - name: bgRemover
        image: "gcr.io/magicbackground/ckit@sha256:3450912129b5d7add41392970941011e700c20ea04956415b4404f0247ac48ba"
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bgRemoverService
spec:
  selector:
    app: bgRemover
  ports:
  - port: 80
    targetPort: 5000

